import type { MonsterDefinition } from "./schema";

const MONSTER_ARCHETYPE_DEFINITIONS = {
  ashling: {
    id: "ashling",
    name: "Ashling",
    behavior: "melee",
    spawnWeight: 38,
    weightPerWave: -1,
    baseLife: 18,
    lifePerWave: 4,
    speed: { min: 39, max: 58, perWave: 1.2 },
    contactDamage: 5,
    contactDamagePerWave: 0.8,
    aggroRange: 720,
    armor: 0,
    evadeChance: 2,
    experience: { base: 6, perWave: 1, perTier: 0.8 },
    visual: {
      sprite: "/monsters/ashling.png",
      corpse: "/monsters/ashling-corpse.png",
      scale: 0.5,
      originY: 0.78,
      body: 0x8e3d42,
      accent: 0xd36b4e,
      sheet: {
        url: "/monsters/ashling-sheet.png",
        frameWidth: 256,
        frameHeight: 256,
        frameCount: 8,
        frameRate: 5,
        aggroFrameRate: 7,
        scale: 0.28,
        originY: 0.92,
      },
    },
    sfx: {
      movement: {
        // The source contains several authored steps. Slice them into short,
        // animation-driven variations rather than overlapping the ten-second file.
        samples: [
          { url: "/sfx/ashling-idle.m4a", offset: 0.08, duration: 0.5 },
          { url: "/sfx/ashling-idle.m4a", offset: 0.92, duration: 0.5 },
          { url: "/sfx/ashling-idle.m4a", offset: 1.78, duration: 0.5 },
          { url: "/sfx/ashling-idle.m4a", offset: 2.66, duration: 0.5 },
        ],
        frameEvents: [1, 5],
        volume: 0.34,
        radius: 520,
        maxVoices: 4,
        groupCooldownMilliseconds: 70,
        emitterCooldownMilliseconds: 240,
        pitchVariation: 0.045,
      },
      aggro: {
        samples: [{ url: "/sfx/ashling-aggro.m4a" }],
        volume: 0.72,
        radius: 760,
        maxVoices: 2,
        groupCooldownMilliseconds: 180,
        pitchVariation: 0.035,
      },
    },
  },
  "cinder-spitter": {
    id: "cinder-spitter",
    name: "Cinder Spitter",
    behavior: "ranged",
    spawnWeight: 16,
    weightPerWave: 1.8,
    minimumWave: 1,
    baseLife: 13,
    lifePerWave: 3,
    speed: { min: 31, max: 43, perWave: 0.8 },
    contactDamage: 4.5,
    contactDamagePerWave: 0.65,
    aggroRange: 860,
    armor: 0,
    evadeChance: 5,
    experience: { base: 7, perWave: 1.15, perTier: 0.9 },
    visual: {
      sprite: "/monsters/cinder-spitter.png",
      corpse: "/monsters/cinder-spitter-corpse.png",
      scale: 0.5,
      originY: 0.74,
      body: 0x5f3b72,
      accent: 0xd985e8,
    },
    ranged: {
      preferredRange: 270,
      projectileSpeed: 245,
      projectileRange: 560,
      projectileRadius: 8,
      cooldown: 1.75,
      damageEffectiveness: 2.25,
    },
    sfx: {},
  },
  "rift-stalker": {
    id: "rift-stalker",
    name: "Rift Stalker",
    behavior: "jumper",
    spawnWeight: 10,
    weightPerWave: 2.2,
    minimumWave: 2,
    baseLife: 24,
    lifePerWave: 5.2,
    speed: { min: 35, max: 48, perWave: 1 },
    contactDamage: 7,
    contactDamagePerWave: 1,
    aggroRange: 780,
    armor: 8,
    evadeChance: 4,
    experience: { base: 11, perWave: 1.7, perTier: 1.2 },
    visual: {
      sprite: "/monsters/rift-stalker.png",
      corpse: "/monsters/rift-stalker-corpse.png",
      scale: 0.53,
      originY: 0.74,
      body: 0x315f6d,
      accent: 0x58d0cf,
    },
    jump: { cooldown: 2.8, distance: 175, duration: 0.36, damageEffectiveness: 1.5 },
    sfx: {},
  },
  "ironhide-brute": {
    id: "ironhide-brute",
    name: "Ironhide Brute",
    behavior: "melee",
    spawnWeight: 8,
    weightPerWave: 0.8,
    minimumWave: 2,
    baseLife: 46,
    lifePerWave: 8,
    speed: { min: 20, max: 28, perWave: 0.45 },
    contactDamage: 10,
    contactDamagePerWave: 1.35,
    aggroRange: 650,
    armor: 42,
    evadeChance: 0,
    experience: { base: 15, perWave: 2.4, perTier: 1.6 },
    visual: {
      sprite: "/monsters/ironhide-brute.png",
      corpse: "/monsters/ironhide-brute-corpse.png",
      scale: 0.68,
      originY: 0.78,
      body: 0x4b4b49,
      accent: 0xb18b5d,
    },
    sfx: {},
  },
  "ember-skitter": {
    id: "ember-skitter",
    name: "Ember Skitter",
    behavior: "melee",
    spawnWeight: 18,
    weightPerWave: 1.5,
    baseLife: 8,
    lifePerWave: 1.8,
    speed: { min: 76, max: 98, perWave: 2.2 },
    contactDamage: 3,
    contactDamagePerWave: 0.45,
    aggroRange: 800,
    armor: 0,
    evadeChance: 14,
    experience: { base: 4, perWave: 0.65, perTier: 0.55 },
    visual: {
      sprite: "/monsters/ember-skitter.png",
      corpse: "/monsters/ember-skitter-corpse.png",
      scale: 0.4,
      originY: 0.7,
      body: 0x9a4b27,
      accent: 0xffa33c,
    },
    sfx: {},
  },
} as const satisfies Record<string, MonsterDefinition>;

export type MonsterArchetypeId = keyof typeof MONSTER_ARCHETYPE_DEFINITIONS;
export const MONSTER_ARCHETYPES: Record<MonsterArchetypeId, MonsterDefinition> = MONSTER_ARCHETYPE_DEFINITIONS;
