import type { MonsterDefinition } from "./schema";

const MONSTER_ARCHETYPE_DEFINITIONS = {
  ashling: {
    id: "ashling",
    name: "Ashling",
    behavior: "melee",
    spawnWeight: 38,
    weightPerWave: -1,
    baseLife: 18,
    lifePerWave: 4,
    speed: { min: 39, max: 58, perWave: 1.2 },
    contactDamage: 5,
    contactDamagePerWave: 0.8,
    aggroRange: 720,
    armor: 0,
    evadeChance: 2,
    experience: { base: 6, perWave: 1, perTier: 0.8 },
    visual: { scale: 1.6, body: 0x8e3d42, accent: 0xd36b4e },
  },
  "cinder-spitter": {
    id: "cinder-spitter",
    name: "Cinder Spitter",
    behavior: "ranged",
    spawnWeight: 16,
    weightPerWave: 1.8,
    minimumWave: 1,
    baseLife: 13,
    lifePerWave: 3,
    speed: { min: 31, max: 43, perWave: 0.8 },
    contactDamage: 4.5,
    contactDamagePerWave: 0.65,
    aggroRange: 860,
    armor: 0,
    evadeChance: 5,
    experience: { base: 7, perWave: 1.15, perTier: 0.9 },
    visual: { scale: 1.5, body: 0x5f3b72, accent: 0xd985e8 },
    ranged: { preferredRange: 270, projectileSpeed: 245, cooldown: 1.75, damageEffectiveness: 2.25 },
  },
  "rift-stalker": {
    id: "rift-stalker",
    name: "Rift Stalker",
    behavior: "jumper",
    spawnWeight: 10,
    weightPerWave: 2.2,
    minimumWave: 2,
    baseLife: 24,
    lifePerWave: 5.2,
    speed: { min: 35, max: 48, perWave: 1 },
    contactDamage: 7,
    contactDamagePerWave: 1,
    aggroRange: 780,
    armor: 8,
    evadeChance: 4,
    experience: { base: 11, perWave: 1.7, perTier: 1.2 },
    visual: { scale: 1.72, body: 0x315f6d, accent: 0x58d0cf },
    jump: { cooldown: 2.8, distance: 175, duration: 0.36, damageEffectiveness: 1.5 },
  },
  "ironhide-brute": {
    id: "ironhide-brute",
    name: "Ironhide Brute",
    behavior: "melee",
    spawnWeight: 8,
    weightPerWave: 0.8,
    minimumWave: 2,
    baseLife: 46,
    lifePerWave: 8,
    speed: { min: 20, max: 28, perWave: 0.45 },
    contactDamage: 10,
    contactDamagePerWave: 1.35,
    aggroRange: 650,
    armor: 42,
    evadeChance: 0,
    experience: { base: 15, perWave: 2.4, perTier: 1.6 },
    visual: { scale: 2.05, body: 0x4b4b49, accent: 0xb18b5d },
  },
  "ember-skitter": {
    id: "ember-skitter",
    name: "Ember Skitter",
    behavior: "melee",
    spawnWeight: 18,
    weightPerWave: 1.5,
    baseLife: 8,
    lifePerWave: 1.8,
    speed: { min: 76, max: 98, perWave: 2.2 },
    contactDamage: 3,
    contactDamagePerWave: 0.45,
    aggroRange: 800,
    armor: 0,
    evadeChance: 14,
    experience: { base: 4, perWave: 0.65, perTier: 0.55 },
    visual: { scale: 1.25, body: 0x9a4b27, accent: 0xffa33c },
  },
} as const satisfies Record<string, MonsterDefinition>;

export type MonsterArchetypeId = keyof typeof MONSTER_ARCHETYPE_DEFINITIONS;
export const MONSTER_ARCHETYPES: Record<MonsterArchetypeId, MonsterDefinition> = MONSTER_ARCHETYPE_DEFINITIONS;
