// Loudness calibration, generated by the offline analysis (window.__soundForge.calibrate() in
// dev/audio.html). Each SFX trim is the voice gain (dB) that brings a recipe's measured loudness
// (max 200 ms K-weighted, power-averaged over 4 renders with different seeds and start offsets,
// measured with the combat bus compressor bypassed) onto its `target` in sfx.ts. Music trims
// bring each track's most intense state onto MUSIC_TARGET (the tracks' level curves lift their
// calmer states). Re-run the calibration after changing a recipe.
import type { MusicId, SfxId } from '../contracts/audio';

export const SFX_TRIM_DB: Partial<Record<SfxId, number>> = {
  castEmber: -1.9,
  castNova: -12.4,
  castWave: -18.5,
  castFrost: -3.6,
  castArc: 2.3,
  dash: -7.4,
  ward: -2.3,
  notEnoughFocus: -7.7,
  hitFire: -3.9,
  hitCold: 0.8,
  hitLightning: 2.4,
  hitVoid: -6.1,
  hitPhysical: -7.3,
  crit: -11.5,
  evade: -7.6,
  monsterDeath: -8.3,
  monsterDeathBig: -14.3,
  monsterAttack: 1.6,
  monsterSpit: -2,
  monsterLeap: -6.7,
  monsterSlam: -12.7,
  heraldCall: -9.9,
  bossRoar: -13.2,
  bossSlam: -12,
  eruption: -15.7,
  playerHurt: -6.7,
  playerDeath: -5.9,
  levelUp: -1.9,
  flaskLife: -1.6,
  flaskFocus: -0.6,
  allyJoin: -6.8,
  partyInvite: 3.1,
  chat: -0.4,
  dropNormal: -4.8,
  dropMagic: -5.2,
  dropRare: -3.3,
  dropUnique: -9.7,
  dropCurrency: 0,
  dropMap: -1.7,
  pickupItem: -0.7,
  pickupCurrency: 2.3,
  mote: -0.3,
  waveTell: -9.1,
  waveStart: -8.5,
  bossSpawn: -11.7,
  cleared: -5,
  chestOpen: -0.9,
  portalOpen: -6.3,
  portalEnter: -11,
  uiClick: 2.3,
  uiHover: 4.3,
  uiOpen: -3.8,
  uiClose: -5.1,
  uiError: -2.8,
  equip: -1.3,
  craftArm: -8,
  craftApply: -9.6,
  craftRare: 1,
  craftScar: 0.2,
  craftFinish: -6.9,
  craftCorrupt: -11.6,
  buy: 0.8,
  // wave 5: player debuffs
  debuffChill: -1.9,
  debuffFreeze: -10.1,
  debuffRoot: 1.6,
  debuffBurn: -16.3,
  debuffBleed: -2.3,
  debuffShock: -0.1,
  debuffWither: -9.5,
  debuffCleanse: -6.6,
  // wave 5: Rimed Ossuary
  boneRattle: -4.4,
  ghostWail: -11.8,
  webShot: -1.1,
  wispPulse: -2.3,
  wispBurst: -7.5,
  golemSlam: -14,
  choirSing: -7.8,
  wardenNova: -13.2,
  glacialSpikes: -7.7,
  icePrison: -2.3,
  blizzardLoop: -11.7,
  // wave 5: Iron Coliseum
  houndBite: -0.6,
  chainThrow: -3.3,
  crossbowAim: 2.4,
  crossbowShot: -5.7,
  shieldBlock: -3.1,
  tarSplat: -5.3,
  chainWhirl: -0.1,
  varkusCharge: -8.6,
  varkusWhirl: 1.6,
  executionMark: -5.1,
  arenaSpikes: -7.7,
  crowdRoar: -8.6,
};

/**
 * Whole-mix gain before the master limiter (dB). Targets and trims are measured on the raw mix
 * before it; this lifts the finished mix toward typical game loudness. Measured headroom: the
 * loudest single sound peaks at −2.9 dBFS and a 200 plays/s frame-batched stress at −3.7 dBFS
 * before this gain, against a −1.5 dBFS limiter, so the limiter only touches rare overs.
 */
export const MIX_GAIN_DB = 2;

/** Integrated loudness targets for music at full music volume (under the combat SFX, which peak −24…−12). */
export const MUSIC_TARGET: Record<MusicId, number> = { title: -23, hideout: -25, map: -25, boss: -23 };

export const MUSIC_TRIM_DB: Partial<Record<MusicId, number>> = { title: 0.5, hideout: 0.1, map: -4.2, boss: -5.1 };
