// Procedural test sprites for the renderer sandbox (dev/render.html). The real game art is generated by the art
// module; this set only needs to exercise every renderer feature: tiles with emissive lava, an animated hero with a
// glowing wand, monsters with glowing eyes, projectiles, fx sprites and props.
import type { PixelImage, SpriteDef } from '../../contracts/art';

type Rgb = readonly [number, number, number];

const hex = (h: string): Rgb => {
  const n = parseInt(h.slice(1), 16);
  return [(n >> 16) & 255, (n >> 8) & 255, n & 255];
};

export const PAL = {
  ink: hex('#0d0b0e'),
  coal: hex('#1a1619'),
  char: hex('#2a2326'),
  iron: hex('#3b3438'),
  stone: hex('#5a5057'),
  stoneLight: hex('#7d7278'),
  bone: hex('#cbbfa8'),
  parchment: hex('#e8dcc0'),
  moss: hex('#4b5a3a'),
  olive: hex('#6e7447'),
  rust: hex('#7a3b24'),
  blood: hex('#7a1e22'),
  burgundy: hex('#5a1a2a'),
  ochre: hex('#b8862f'),
  gold: hex('#e0b04a'),
  ember: hex('#e8662a'),
  flame: hex('#ff9a3c'),
  hot: hex('#ffe7a8'),
  frost: hex('#7fc6e8'),
  ice: hex('#d4f1ff'),
  mana: hex('#4a7bd6'),
  void: hex('#7b3fa0'),
  voidGlow: hex('#c07bff'),
};

/** Small deterministic PRNG (mulberry32) so the art is identical every load. */
export function prng(seed: number): () => number {
  let s = seed >>> 0;
  return () => {
    s = (s + 0x6d2b79f5) >>> 0;
    let t = s;
    t = Math.imul(t ^ (t >>> 15), t | 1);
    t ^= t + Math.imul(t ^ (t >>> 7), t | 61);
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

function mix(a: Rgb, b: Rgb, t: number): Rgb {
  return [a[0] + (b[0] - a[0]) * t, a[1] + (b[1] - a[1]) * t, a[2] + (b[2] - a[2]) * t];
}

class Img {
  readonly data: Uint8ClampedArray;
  constructor(readonly w: number, readonly h: number) {
    this.data = new Uint8ClampedArray(w * h * 4);
  }
  set(x: number, y: number, c: Rgb, a = 255): void {
    x = Math.round(x);
    y = Math.round(y);
    if (x < 0 || y < 0 || x >= this.w || y >= this.h) return;
    const o = (y * this.w + x) * 4;
    this.data[o] = c[0];
    this.data[o + 1] = c[1];
    this.data[o + 2] = c[2];
    this.data[o + 3] = a;
  }
  alpha(x: number, y: number): number {
    if (x < 0 || y < 0 || x >= this.w || y >= this.h) return 0;
    return this.data[(y * this.w + x) * 4 + 3];
  }
  rgb(x: number, y: number): Rgb {
    const o = (y * this.w + x) * 4;
    return [this.data[o], this.data[o + 1], this.data[o + 2]];
  }
  rect(x0: number, y0: number, w: number, h: number, c: Rgb, a = 255): void {
    for (let y = y0; y < y0 + h; y++) for (let x = x0; x < x0 + w; x++) this.set(x, y, c, a);
  }
  ellipse(cx: number, cy: number, rx: number, ry: number, shade: (nx: number, ny: number) => Rgb | null): void {
    for (let y = Math.floor(cy - ry); y <= Math.ceil(cy + ry); y++) {
      for (let x = Math.floor(cx - rx); x <= Math.ceil(cx + rx); x++) {
        const nx = (x + 0.5 - cx) / rx;
        const ny = (y + 0.5 - cy) / ry;
        if (nx * nx + ny * ny > 1) continue;
        const c = shade(nx, ny);
        if (c) this.set(x, y, c);
      }
    }
  }
  line(x0: number, y0: number, x1: number, y1: number, c: Rgb, a = 255): void {
    const n = Math.max(Math.abs(x1 - x0), Math.abs(y1 - y0), 1);
    for (let i = 0; i <= n; i++) this.set(x0 + ((x1 - x0) * i) / n, y0 + ((y1 - y0) * i) / n, c, a);
  }
  /** 1px dark outline around the opaque silhouette (hand-pixelled look). */
  outline(c: Rgb): void {
    const add: [number, number][] = [];
    for (let y = 0; y < this.h; y++) {
      for (let x = 0; x < this.w; x++) {
        if (this.alpha(x, y) > 0) continue;
        if (this.alpha(x - 1, y) > 128 || this.alpha(x + 1, y) > 128 || this.alpha(x, y - 1) > 128 || this.alpha(x, y + 1) > 128) add.push([x, y]);
      }
    }
    for (const [x, y] of add) this.set(x, y, c);
  }
  image(): PixelImage {
    return { width: this.w, height: this.h, data: this.data };
  }
}

function def(id: string, frames: Img[], emissive: Img[] | null, anchorX: number, anchorY: number, fps = 8, loop = true): SpriteDef {
  return {
    id,
    width: frames[0].w,
    height: frames[0].h,
    frames: frames.map((f) => f.image()),
    emissive: emissive ? emissive.map((f) => f.image()) : undefined,
    anchorX,
    anchorY,
    fps,
    loop,
  };
}

// ---------------------------------------------------------------------------------------------------------------
// Tiles
// ---------------------------------------------------------------------------------------------------------------

function floorTile(seed: number, lava: boolean): [Img, Img] {
  const r = prng(seed);
  const img = new Img(16, 16);
  const em = new Img(16, 16);
  // Irregular flagstones: split the tile into 2-3 slabs with ink mortar.
  const splitX = 5 + Math.floor(r() * 6);
  const splitY = 5 + Math.floor(r() * 6);
  const vertical = r() < 0.5;
  for (let y = 0; y < 16; y++) {
    for (let x = 0; x < 16; x++) {
      const slab = vertical ? (x < splitX ? 0 : y < splitY ? 1 : 2) : y < splitY ? 0 : x < splitX ? 1 : 2;
      const tone = [0.1, 0.3, 0.18][slab] + r() * 0.16;
      let c = mix(PAL.coal, PAL.iron, tone);
      if (r() < 0.05) c = mix(c, PAL.stone, 0.5);
      if (r() < 0.03) c = mix(c, PAL.moss, 0.45);
      img.set(x, y, c);
    }
  }
  // Mortar lines + bevel highlights.
  const mortar = (x: number, y: number) => img.set(x, y, mix(PAL.ink, PAL.coal, 0.3));
  for (let i = 0; i < 16; i++) {
    mortar(i, 15);
    mortar(15, i);
  }
  if (vertical) {
    for (let y = 0; y < 16; y++) mortar(splitX, y);
    for (let x = splitX; x < 16; x++) mortar(x, splitY);
  } else {
    for (let x = 0; x < 16; x++) mortar(x, splitY);
    for (let y = splitY; y < 16; y++) mortar(splitX, y);
  }
  for (let i = 0; i < 15; i++) {
    if (img.rgb(i, 0)[0] > 20) img.set(i, 0, mix(img.rgb(i, 0), PAL.stoneLight, 0.25));
    if (img.rgb(0, i)[0] > 20) img.set(0, i, mix(img.rgb(0, i), PAL.stoneLight, 0.18));
  }
  if (lava) {
    // A meandering crack with a molten core: dark rust lips in albedo, flame/hot glow in the emissive mask.
    let x = 2 + r() * 4;
    let y = 3 + r() * 10;
    let dir = r() * 0.8 - 0.4;
    for (let i = 0; i < 13; i++) {
      const ix = Math.floor(x);
      const iy = Math.floor(y);
      img.set(ix, iy, mix(PAL.rust, PAL.ink, 0.35));
      img.set(ix, iy + 1, mix(PAL.rust, PAL.ink, 0.65));
      em.set(ix, iy, i % 4 === 2 ? PAL.hot : PAL.flame, 190 + Math.floor(r() * 60));
      em.set(ix, iy + 1, PAL.ember, 70);
      x += 1;
      dir += (r() - 0.5) * 0.9;
      dir = Math.max(-1, Math.min(1, dir));
      y += dir;
      if (y < 1 || y > 14) dir = -dir;
    }
  }
  return [img, em];
}

function detailTile(kind: number, seed: number): [Img, Img] {
  const r = prng(seed);
  const img = new Img(16, 16);
  const em = new Img(16, 16);
  if (kind === 0) {
    // Bones
    img.line(3, 10, 11, 7, PAL.bone);
    img.set(2, 10, PAL.parchment);
    img.set(2, 11, PAL.parchment);
    img.set(12, 6, PAL.parchment);
    img.set(12, 7, PAL.parchment);
    img.ellipse(6, 5, 2, 1.6, () => PAL.bone);
    img.set(5, 5, PAL.ink);
    img.set(7, 5, PAL.ink);
  } else if (kind === 1) {
    // Rubble
    for (let i = 0; i < 5; i++) {
      const x = 2 + r() * 11;
      const y = 3 + r() * 10;
      img.ellipse(x, y, 1.2 + r() * 1.3, 1 + r(), (nx, ny) => (nx + ny < -0.3 ? PAL.stoneLight : ny > 0.3 ? PAL.char : PAL.stone));
    }
  } else if (kind === 2) {
    // Rune circle with a faint ember glow
    for (let a = 0; a < 24; a++) {
      const t = (a / 24) * Math.PI * 2;
      const x = 8 + Math.cos(t) * 5.5;
      const y = 8 + Math.sin(t) * 4;
      img.set(x, y, PAL.rust);
      if (a % 3 === 0) em.set(x, y, PAL.ember, 150);
    }
    img.line(8, 5, 8, 11, PAL.rust);
    em.set(8, 8, PAL.flame, 200);
  } else {
    // Moss patch
    for (let i = 0; i < 26; i++) {
      const x = 4 + r() * 8;
      const y = 5 + r() * 6;
      img.set(x, y, r() < 0.5 ? PAL.moss : PAL.olive, 220);
    }
  }
  return [img, em];
}

// ---------------------------------------------------------------------------------------------------------------
// Characters
// ---------------------------------------------------------------------------------------------------------------

/** Hooded sorceress ~18x26, facing south or east, with an ember-tipped wand. */
function heroFrame(dir: 'south' | 'east', phase: number, running: boolean): [Img, Img] {
  const img = new Img(18, 27);
  const em = new Img(18, 27);
  const bob = running ? (phase % 3 === 1 ? -1 : 0) : phase === 2 ? -1 : 0;
  const cx = 9;
  const top = 2 + bob;
  // Legs / boots
  const stride = running ? [0, 2, 1, 0, -2, -1][phase % 6] : 0;
  img.rect(cx - 3 + Math.min(0, stride), 23, 2, 2, PAL.coal);
  img.rect(cx + 1 + Math.max(0, stride), 23, 2, 2, PAL.coal);
  // Robe: flared trapezoid with shaded folds
  for (let y = top + 10; y <= 23; y++) {
    const t = (y - top - 10) / (13 - bob);
    const half = 3.5 + t * 2.8;
    for (let x = Math.floor(cx - half); x <= Math.ceil(cx + half - 1); x++) {
      const nx = (x + 0.5 - cx) / half;
      let c = nx < -0.45 ? PAL.iron : nx > 0.4 ? PAL.coal : PAL.char;
      if (dir === 'south' && Math.abs(nx) < 0.22) c = PAL.burgundy;
      if (y === 23) c = PAL.burgundy;
      if ((x + y) % 5 === 0 && y > top + 13 && Math.abs(nx) > 0.2) c = mix(c, PAL.ink, 0.4);
      img.set(x, y, c);
    }
  }
  // Mantle / shoulders
  img.ellipse(cx, top + 10, 5, 2.6, (nx) => (nx < -0.3 ? PAL.blood : nx > 0.4 ? mix(PAL.burgundy, PAL.ink, 0.35) : PAL.burgundy));
  // Hood
  const hx = dir === 'east' ? cx + 1 : cx;
  img.ellipse(hx, top + 5, 4.4, 4.8, (nx, ny) => (nx + ny < -0.6 ? PAL.blood : nx > 0.45 || ny > 0.55 ? mix(PAL.burgundy, PAL.ink, 0.35) : PAL.burgundy));
  img.set(hx, top, PAL.blood);
  // Face opening
  if (dir === 'south') {
    img.rect(hx - 2, top + 5, 4, 3, PAL.bone);
    img.rect(hx - 2, top + 5, 4, 1, mix(PAL.bone, PAL.ink, 0.55));
    img.set(hx - 1, top + 6, PAL.ink);
    img.set(hx + 1, top + 6, PAL.ink);
    // Hair strands framing the face
    img.line(hx - 3, top + 5, hx - 3, top + 10, PAL.parchment);
    img.line(hx + 2, top + 5, hx + 2, top + 9, PAL.parchment);
  } else {
    img.rect(hx + 1, top + 5, 3, 3, PAL.bone);
    img.set(hx + 1, top + 5, mix(PAL.bone, PAL.ink, 0.55));
    img.set(hx + 2, top + 6, PAL.ink);
    img.line(hx - 1, top + 6, hx - 2, top + 11, PAL.parchment);
  }
  // Wand arm + wand with ember tip
  const swing = running ? [0, 1, 1, 0, -1, -1][phase % 6] : 0;
  const wx = dir === 'east' ? cx + 5 : cx - 6;
  const wy = top + 12 + swing;
  img.set(wx + (dir === 'east' ? -1 : 1), wy + 1, PAL.bone);
  img.line(wx, wy + 3, wx + (dir === 'east' ? 2 : -1), wy - 5, PAL.rust);
  const tipX = wx + (dir === 'east' ? 2 : -1);
  const tipY = wy - 6;
  img.set(tipX, tipY, PAL.hot);
  img.set(tipX, tipY + 1, PAL.flame);
  em.set(tipX, tipY, PAL.hot, 255);
  em.set(tipX, tipY + 1, PAL.flame, 230);
  em.set(tipX - 1, tipY, PAL.ember, 120);
  em.set(tipX + 1, tipY, PAL.ember, 120);
  em.set(tipX, tipY - 1, PAL.flame, 150);
  img.outline(PAL.ink);
  return [img, em];
}

/** Hunched ash creature with ember cracks and glowing eyes (faces east). */
function ashlingFrame(phase: number): [Img, Img] {
  const img = new Img(15, 13);
  const em = new Img(15, 13);
  const bob = phase % 2 === 1 ? -1 : 0;
  const leg = [0, 1, 0, -1][phase % 4];
  img.rect(4 + leg, 10, 2, 2, PAL.coal);
  img.rect(9 - leg, 10, 2, 2, PAL.coal);
  img.ellipse(7, 7 + bob, 5.2, 3.8, (nx, ny) => (nx + ny < -0.7 ? PAL.stone : ny > 0.35 ? PAL.coal : nx > 0.5 ? PAL.char : PAL.iron));
  img.ellipse(11, 5 + bob, 2.8, 2.4, (nx, ny) => (ny < -0.2 ? PAL.stone : PAL.iron));
  // Ember crack along the back
  const crack: [number, number][] = [[4, 5], [5, 6], [6, 5], [7, 6], [8, 5]];
  for (const [x, y] of crack) {
    img.set(x, y + bob, PAL.rust);
    em.set(x, y + bob, PAL.ember, 200);
  }
  // Eyes
  img.set(12, 5 + bob, PAL.hot);
  img.set(13, 5 + bob, PAL.flame);
  em.set(12, 5 + bob, PAL.hot, 255);
  em.set(13, 5 + bob, PAL.flame, 255);
  img.outline(PAL.ink);
  return [img, em];
}

/** Small, fast skitter with a glowing ember back. */
function skitterFrame(phase: number): [Img, Img] {
  const img = new Img(12, 9);
  const em = new Img(12, 9);
  const l = phase % 2;
  for (let i = 0; i < 3; i++) {
    img.set(3 + i * 2 + l, 7, PAL.coal);
    img.set(3 + i * 2 + (1 - l), 7, PAL.char);
  }
  img.ellipse(6, 4.5, 4, 2.5, (nx, ny) => (ny < -0.3 ? PAL.rust : PAL.char));
  img.set(9, 4, PAL.hot);
  em.set(9, 4, PAL.hot, 255);
  for (let x = 4; x <= 7; x++) em.set(x, 3, PAL.ember, 170);
  img.outline(PAL.ink);
  return [img, em];
}

/** Heavy armoured brute (faces east). */
function bruteFrame(phase: number): [Img, Img] {
  const img = new Img(24, 23);
  const em = new Img(24, 23);
  const bob = phase % 2 === 1 ? -1 : 0;
  const leg = [0, 1, 0, -1][phase % 4];
  img.rect(6 + leg, 18, 4, 4, PAL.coal);
  img.rect(14 - leg, 18, 4, 4, PAL.coal);
  img.ellipse(12, 12 + bob, 9, 7.5, (nx, ny) =>
    nx + ny < -0.8 ? PAL.stoneLight : ny > 0.45 ? PAL.coal : nx > 0.5 ? PAL.char : (Math.abs(nx * 7) | 0) % 3 === 0 ? PAL.rust : PAL.iron,
  );
  // Riveted plate highlights
  for (let x = 6; x < 18; x += 3) img.set(x, 8 + bob, PAL.stoneLight);
  // Arms
  img.ellipse(20, 13 + bob, 3, 4.5, (nx) => (nx < 0 ? PAL.iron : PAL.char));
  img.ellipse(4, 13 + bob, 2.6, 4, (nx) => (nx < 0 ? PAL.stone : PAL.iron));
  // Visor slit
  for (let x = 14; x <= 18; x++) {
    img.set(x, 8 + bob, PAL.ember);
    em.set(x, 8 + bob, x === 16 ? PAL.hot : PAL.flame, 255);
  }
  img.outline(PAL.ink);
  return [img, em];
}

// ---------------------------------------------------------------------------------------------------------------
// FX, projectiles, props, drops
// ---------------------------------------------------------------------------------------------------------------

function radial(size: number, fn: (d: number) => number, color: Rgb = [255, 255, 255]): Img {
  const img = new Img(size, size);
  const c = (size - 1) / 2;
  for (let y = 0; y < size; y++) {
    for (let x = 0; x < size; x++) {
      const d = Math.hypot(x - c, y - c) / (size / 2);
      const a = fn(d);
      if (a > 0) img.set(x, y, color, Math.round(Math.min(1, a) * 255));
    }
  }
  return img;
}

function lance(): [Img, Img] {
  const img = new Img(14, 5);
  const em = new Img(14, 5);
  for (let x = 0; x < 14; x++) {
    const t = x / 13;
    const halfW = t > 0.75 ? 2 : t > 0.35 ? 1 : 0;
    for (let dy = -halfW; dy <= halfW; dy++) {
      const edge = Math.abs(dy) === halfW && halfW > 0;
      const c = t > 0.8 && !edge ? PAL.hot : t > 0.45 ? (edge ? PAL.ember : PAL.flame) : PAL.ember;
      const a = Math.round(120 + 135 * t);
      img.set(x, 2 + dy, c, a);
      em.set(x, 2 + dy, c, a);
    }
  }
  return [img, em];
}

function orb(): [Img, Img] {
  const img = radial(9, (d) => (d < 0.95 ? 1 : 0), PAL.void);
  const em = radial(9, (d) => (d < 0.95 ? 1.1 - d : 0), PAL.voidGlow);
  img.set(3, 3, PAL.voidGlow);
  em.set(4, 4, [255, 230, 255], 255);
  return [img, em];
}

function pillar(): [Img, Img] {
  const img = new Img(16, 42);
  const em = new Img(16, 42);
  const r = prng(7);
  for (let y = 4; y < 38; y++) {
    for (let x = 3; x < 13; x++) {
      const nx = (x - 3) / 9;
      let c = nx < 0.25 ? PAL.stoneLight : nx < 0.7 ? PAL.stone : PAL.iron;
      if ((y % 9 === 0 && y > 4) || r() < 0.06) c = mix(c, PAL.char, 0.5);
      img.set(x, y, c);
    }
  }
  img.rect(1, 0, 14, 4, PAL.stone);
  img.rect(1, 0, 14, 1, PAL.stoneLight);
  img.rect(1, 3, 14, 1, PAL.iron);
  img.rect(2, 38, 12, 4, PAL.iron);
  img.rect(2, 38, 12, 1, PAL.stone);
  // Carved ember spiral
  const sp: [number, number][] = [[8, 18], [9, 18], [9, 19], [8, 20], [7, 20], [6, 19], [6, 18], [7, 16], [9, 16], [10, 17], [10, 19]];
  for (const [x, y] of sp) {
    img.set(x, y, PAL.rust);
    em.set(x, y, PAL.ember, 150);
  }
  img.outline(PAL.ink);
  return [img, em];
}

function brazier(phase: number): [Img, Img] {
  const img = new Img(14, 22);
  const em = new Img(14, 22);
  // Tripod legs
  img.line(4, 21, 6, 13, PAL.coal);
  img.line(10, 21, 8, 13, PAL.coal);
  img.line(7, 21, 7, 13, PAL.char);
  // Bowl
  img.ellipse(7, 12, 5.5, 2.6, (nx, ny) => (ny < -0.2 ? PAL.rust : nx < -0.3 ? PAL.stone : PAL.iron));
  // Flames (animated)
  const r = prng(100 + phase);
  for (let i = 0; i < 16; i++) {
    const x = 4 + Math.floor(r() * 7);
    const h = 2 + Math.floor(r() * (x > 5 && x < 9 ? 7 : 4));
    for (let y = 0; y < h; y++) {
      const t = y / h;
      const c = t < 0.3 ? PAL.hot : t < 0.7 ? PAL.flame : PAL.ember;
      img.set(x, 10 - y, c, 255);
      em.set(x, 10 - y, c, Math.round(255 * (1 - t * 0.5)));
    }
  }
  img.outline(PAL.ink);
  return [img, em];
}

function crystal(): [Img, Img] {
  const img = new Img(13, 19);
  const em = new Img(13, 19);
  const shard = (x0: number, h: number, w: number) => {
    for (let y = 0; y < h; y++) {
      const half = Math.max(0.5, (w * (h - y)) / h / 2);
      for (let x = Math.round(x0 - half); x <= Math.round(x0 + half); x++) {
        const light = x < x0;
        const c = y < 2 ? PAL.mana : light ? PAL.ice : PAL.frost;
        const yy = 18 - y;
        img.set(x, yy, c);
        em.set(x, yy, light ? PAL.ice : PAL.frost, light ? 120 : 50);
      }
    }
  };
  shard(6, 17, 5);
  shard(3, 10, 3.5);
  shard(10, 12, 3.5);
  img.outline(PAL.ink);
  return [img, em];
}

function wandDrop(): Img {
  const img = new Img(12, 8);
  img.line(1, 6, 9, 2, PAL.rust);
  img.line(1, 7, 9, 3, PAL.char);
  img.set(10, 1, PAL.gold);
  img.set(10, 2, PAL.ochre);
  img.set(11, 1, PAL.hot);
  img.outline(PAL.ink);
  return img;
}

function currencyDrop(): [Img, Img] {
  const img = radial(7, (d) => (d < 0.85 ? 1 : 0), PAL.ochre);
  img.set(2, 2, PAL.hot);
  img.set(3, 2, PAL.gold);
  img.set(2, 3, PAL.gold);
  const em = new Img(7, 7);
  em.set(2, 2, PAL.hot, 200);
  img.outline(PAL.ink);
  return [img, em];
}

export function makeTestArt(): SpriteDef[] {
  const defs: SpriteDef[] = [];

  const floors: Img[] = [];
  const floorEm: Img[] = [];
  for (let i = 0; i < 8; i++) {
    const [a, e] = floorTile(1000 + i * 17, false);
    floors.push(a);
    floorEm.push(e);
  }
  for (let i = 0; i < 4; i++) {
    const [a, e] = floorTile(5000 + i * 31, true);
    floors.push(a);
    floorEm.push(e);
  }
  defs.push(def('tile/test/floor', floors, floorEm, 0, 0, 0, false));

  const details = [0, 1, 2, 3].map((k) => detailTile(k, 77 + k));
  defs.push(def('tile/test/detail', details.map((d) => d[0]), details.map((d) => d[1]), 0, 0, 0, false));

  for (const dir of ['south', 'east'] as const) {
    const run = [0, 1, 2, 3, 4, 5].map((p) => heroFrame(dir, p, true));
    defs.push(def(`hero/run/${dir}`, run.map((f) => f[0]), run.map((f) => f[1]), 9, 26, 10));
    const idle = [0, 1, 2, 3].map((p) => heroFrame(dir, p, false));
    defs.push(def(`hero/idle/${dir}`, idle.map((f) => f[0]), idle.map((f) => f[1]), 9, 26, 4));
  }

  const ash = [0, 1, 2, 3].map(ashlingFrame);
  defs.push(def('mon/ashling', ash.map((f) => f[0]), ash.map((f) => f[1]), 7, 12, 8));
  const sk = [0, 1].map(skitterFrame);
  defs.push(def('mon/skitter', sk.map((f) => f[0]), sk.map((f) => f[1]), 6, 8, 12));
  const br = [0, 1, 2, 3].map(bruteFrame);
  defs.push(def('mon/brute', br.map((f) => f[0]), br.map((f) => f[1]), 12, 22, 5));

  const [la, le] = lance();
  defs.push(def('proj/lance', [la], [le], 10, 2.5, 0, false));
  const [oa, oe] = orb();
  defs.push(def('proj/orb', [oa], [oe], 4.5, 4.5, 0, false));
  // Same orb with the integer centre anchor the real art uses (floor(w / 2)).
  defs.push(def('proj/orb4', [oa], [oe], 4, 4, 0, false));

  const spark = new Img(3, 3);
  spark.set(1, 1, [255, 255, 255]);
  for (const [x, y] of [[0, 1], [2, 1], [1, 0], [1, 2]] as const) spark.set(x, y, [255, 255, 255], 120);
  defs.push(def('fx/spark', [spark], null, 1.5, 1.5, 0, false));
  const ember = new Img(2, 2);
  ember.rect(0, 0, 2, 2, [255, 255, 255]);
  defs.push(def('fx/ember', [ember], null, 1, 1, 0, false));
  defs.push(def('fx/smoke', [radial(8, (d) => (d < 1 ? (1 - d) * 0.9 : 0), [150, 140, 150])], null, 4, 4, 0, false));
  defs.push(def('fx/glow', [radial(16, (d) => Math.max(0, 1 - d) ** 2)], null, 8, 8, 0, false));
  defs.push(def('fx/shadow', [radial(14, (d) => (d < 1 ? 0.55 - d * 0.25 : 0), [0, 0, 0])], null, 7, 7, 0, false));
  const beam = new Img(5, 40);
  for (let y = 0; y < 40; y++) {
    const t = 1 - y / 39;
    for (let x = 0; x < 5; x++) beam.set(x, y, [255, 255, 255], Math.round(255 * (1 - t) ** 1.5 * (x === 2 ? 1 : x === 1 || x === 3 ? 0.55 : 0.2)));
  }
  defs.push(def('fx/beam', [beam], null, 2.5, 40, 0, false));

  const [pa, pe] = pillar();
  defs.push(def('prop/pillar', [pa], [pe], 8, 41, 0, false));
  const bz = [0, 1, 2, 3].map(brazier);
  defs.push(def('prop/brazier', bz.map((f) => f[0]), bz.map((f) => f[1]), 7, 21, 9));
  const [ca, ce] = crystal();
  defs.push(def('prop/crystal', [ca], [ce], 6.5, 18, 0, false));

  defs.push(def('drop/equipment', [wandDrop()], null, 6, 7, 0, false));
  const [ga, ge] = currencyDrop();
  defs.push(def('drop/currency', [ga], [ge], 3.5, 6, 0, false));
  return defs;
}
